require("julienvincent.core.lazy")
require("julienvincent.core.keymaps")
require("julienvincent.core.autocmds")
require("julienvincent.core.options")
require("julienvincent.core.highlight-groups")
require("julienvincent.behaviours.buffer-switching").init()
